### ISSUE TITLE
counting

### ISSUE THREAD

**Issue by raymin0223** [Lee-Gihun/MicroNet_OSI-AI#6]
@micronet-challenge-submissions

Dear Organizers, we have a question about counting the mask related to pruning.
```
def get_sparse_size(tensor_shape, param_bits, sparsity):
    """Given a tensor shape returns #bits required to store the tensor sparse.
    If sparsity is greater than 0, we do have to store a bit mask to represent
    sparsity.
    Args:
    tensor_shape: list<int>, shape of the tensor
    param_bits: int, number of bits the elements of the tensor represented in.
    sparsity: float, sparsity level. 0 means dense.
    Returns:
    int, number of bits required to represented the tensor in sparse format.
    """
    n_elements = np.prod(tensor_shape)
    c_size = n_elements * param_bits * (1 - sparsity)
    if sparsity > 0:
        c_size += n_elements  # 1 bit binary mask.
    return c_size
```

Following above your `get_sparse_size` function in `counting.py` code,  we calculated the 1 bit binary mask after pruning some weights.

However, after submitting our final score, we realized that pruned weights in our model are just 0 by itself!
Although we have mask parameters in our model, it was just for training model and we can ignore them in inference time.

So we want to ask you whether scoring mask parameters can be excluded in our case.
If it is fine, we want to update our score before you verify our submission :slightly_smiling_face:

Thank you!
TEAM OSI-AI

**Comment by micronet-challenge-submissions** [comment]
Hi Team OSI-AI,

I understand the confusion, since masks are needed during training to simulate sparsity. However, the bitmask rule is designed to take into account the overhead of storing a sparse tensor. If we want to compute on a sparse tensor and skip computation associated with zeros, we need to store the tensor in a compressed format like compressed sparse row (CSR). These storage formats have some storage overhead, since you need to store some metadata for each nonzero value so that you know where it came from in the original tensor. The bitmask rule is designed to take this into account.

Trevor

**Comment by raymin0223** [comment]
Oh thanks for the explanation!

I'll close this issue :)
